apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: flask-app-git
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80        # The port that the service will expose
      targetPort: 9001  # The port on the container where the app is running
      nodePort: 30001  # The port on each node where the service will be exposed
  type: NodePort
